environment:
  matrix:
    - nodejs_version: 0.8
    - nodejs_version: 0.10
    - nodejs_version: 0.11

platform:
  - x64
  - x86

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - node -e "console.log(process.arch);"
  - SET PATH=C:\python27;%PATH%
  - npm install
  - cmd: test.bat

build: off
test: off
deploy: off